### ISSUE TITLE
Reset on FPP Upload

### ISSUE THREAD

**Issue by noman1228** [MartinMueller2003/ESPixelStick#12]
--------- Instructions --------
Please provide answers directly below each section.
--------- Instructions ---------

**ESPixelStick Firmware Version**
All builds currently on web flasher. 
CI from source.

SD cards - ALL (16gb/8gb/2gb exFat, fat32, fat16)

**Hardware Version**
ESP32DEVKIT1 (known legitimate)
ESP32DEVKIT1 (known clone)
AZ-Delivery-DEVKITv4 (wroom32-U)
Freenove wrover-e

All standard defined pins as defined in your existing GPIODefs.
None of you code changed or even touched.
3 outputs (ws2811) loaded with 125 on each port all DDP.
Outputs manually set or uploaded from xlights.

**Binary release or compiled yourself?**
both / either

**Operating System (and version)**
win 11/ kali lts / Ubuntu 24 lts

**Web Browser (and version)**
Chrome 
Opera
Firefox
all latest

**Access Point**
Wifi different channels and modes

**Describe the bug**
When compiled from fresh pull, clean DEV environment.

abort() was called at PC 0x401ce8a7 on core 1

Backtrace: 0x40084bcd:0x3ffb44b0 0x400902e9:0x3ffb44d0 0x400964f9:0x3ffb44f0 0x401ce8a7:0x3ffb4570 0x401ce8ee:0x3ffb4590 0x401cf32f:0x3ffb45b0 0x400fdd29:0x3ffb45d0 0x400fe27b:0x3ffb45f0 0x400fe2ef:0x3ffb4610
  #0  0x40084bcd in panic_abort at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/esp_system/panic.c:408
  #1  0x400902e9 in esp_system_abort at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/esp_system/esp_system.c:137
  #2  0x400964f9 in abort at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/newlib/abort.c:46
  #3  0x401ce8a7 in __cxxabiv1::__terminate(void (*)()) at /builds/idf/crosstool-NG/.build/HOST-x86_64-w64-mingw32/xtensa-esp32-elf/src/gcc/libstdc++-v3/libsupc++/eh_terminate.cc:47
  #4  0x401ce8ee in std::terminate() at /builds/idf/crosstool-NG/.build/HOST-x86_64-w64-mingw32/xtensa-esp32-elf/src/gcc/libstdc++-v3/libsupc++/eh_terminate.cc:57
  #5  0x401cf32f in __cxa_pure_virtual at /builds/idf/crosstool-NG/.build/HOST-x86_64-w64-mingw32/xtensa-esp32-elf/src/gcc/libstdc++-v3/libsupc++/pure.cc:50
  #6  0x400fdd29 in c_InputFPPRemote::StopPlaying() at src/input/InputFPPRemote.cpp:386
  #7  0x400fe27b in c_InputFPPRemote::TaskProcess() at src/input/InputFPPRemote.cpp:263
  #8  0x400fe2ef in FppRemoteTask(void*) at src/input/InputFPPRemote.cpp:58

if you disable FPP once the discovery is   complete, then upload from xlights it's both extremely fast (comparatively) and rock solid.

**Comment by noman1228** [comment]
**From A CI Webflash:**

[07:00:09][FileMgr] Upload File: 'Outro.fseq' Started
[07:00:09]
[07:00:09]abort() was called at PC 0x4018969f on core 1
[07:00:09]
[07:00:09]
[07:00:09]Backtrace: 0x400845f9:0x3ffeb880 0x4008ebe5:0x3ffeb8a0 0x40094df5:0x3ffeb8c0 0x4018969f:0x3ffeb940 0x401896e6:0x3ffeb960 0x401894f3:0x3ffeb980 0x400e4d92:0x3ffeb9a0 0x400e5253:0x3ffeb9c0 0x400e52cf:0x3ffeb9e0
[07:00:09]
[07:00:09]
[07:00:09]
[07:00:09]
[07:00:09]ELF file SHA256: 1f5aca334ef7a193
[07:00:09]
[07:00:09]E (9450) esp_core_dump_flash: Core dump flash config is corrupted! CRC=0x7bd5c66f instead of 0x0
[07:00:09]Rebooting...
[07:00:09]ets Jul 29 2019 12:21:46
[07:00:09]
[07:00:09]rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
[07:00:09]configsip: 0, SPIWP:0xee
[07:00:09]clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
[07:00:09]mode:DIO, clock div:1
[07:00:09]load:0x3fff0030,len:1184
[07:00:09]load:0x40078000,len:13232
[07:00:09]load:0x40080400,len:3028
[07:00:09]entry 0x400805e4
[07:00:09]E (460) esp_core_dump_flash: No core dum���ѥѥ���found!
[07:00:09]E (460) esp_core_dump_flash: No core dump partition found!
[07:00:09]
[07:00:09][   ESP] ESPixelStick v4.0-ci12528122464 (Dec 28 2024 - 16:31:14)
[07:00:09][   ESP] v4.4.7-dirty
[07:00:09][   ESP] CPU Frequency: 240MHz
[07:00:09][   ESP] APB Frequency: 80MHz
[07:00:10][FileMgr] Flash file system initialized. Used = 229376 out of 327680
[07:00:10][FileMgr] Listing directory: /
[07:00:10][FileMgr] 'UpdRecipe.json': 	'784'
[07:00:10][FileMgr] 'admininfo.json': 	'168'
[07:00:10][FileMgr] 'config.json': 	'525'
[07:00:10][FileMgr] 'input_config.json': 	'2062'
[07:00:10][FileMgr] 'output_config.json': 	'10260'
[07:00:10][FileMgr] Listing directory: //www
[07:00:10][FileMgr] 'alexa.html.gz': 	'146'
[07:00:10][FileMgr] 'apa102.html.gz': 	'1503'
[07:00:10][FileMgr] 'artnet.html.gz': 	'385'
[07:00:10][FileMgr] 'ddp.html.gz': 	'144'
[07:00:10][FileMgr] 'dmx.html.gz': 	'455'
[07:00:10][FileMgr] 'e1_31.html.gz': 	'460'
[07:00:10][FileMgr] 'effects.html.gz': 	'1051'
[07:00:10][FileMgr] 'esps.css.gz': 	'13424'
[07:00:10][FileMgr] 'esps.js.gz': 	'63024'
[07:00:10][FileMgr] 'favicon.ico': 	'6450'
[07:00:10][FileMgr] 'fpp_remote.html.gz': 	'385'
[07:00:10][FileMgr] 'gece.html.gz': 	'501'
[07:00:10][FileMgr] 'grinch.html.gz': 	'377'
[07:00:10][FileMgr] 'gs8208.html.gz': 	'1579'
[07:00:10][FileMgr] 'index.html.gz': 	'5404'
[07:00:10][FileMgr] 'mqtt.html.gz': 	'682'
[07:00:10][FileMgr] 'relay.html.gz': 	'507'
[07:00:10][FileMgr] 'renard.html.gz': 	'528'
[07:00:10][FileMgr] 'serial.html.gz': 	'619'
[07:00:10][FileMgr] 'servo_pca9685.html.gz': 	'523'
[07:00:10][FileMgr] 'tls3001.html.gz': 	'1503'
[07:00:11][FileMgr] 'tm1814.html.gz': 	'1617'
[07:00:11][FileMgr] 'ucs1903.html.gz': 	'1580'
[07:00:11][FileMgr] 'ucs8903.html.gz': 	'1585'
[07:00:11][FileMgr] 'ws2801.html.gz': 	'1502'
[07:00:11][FileMgr] 'ws2811.html.gz': 	'1582'
[07:00:11][FileMgr] Set SD speed to 25Mhz
[07:00:11][FileMgr] SD Card Size: 7948MB
[07:00:11][FileMgr] Configuration File: '/config.json' loaded.
[07:00:11][FileMgr] Configuration File: '/input_config.json' loaded.
[07:00:12][FileMgr] Configuration File: '/output_config.json' loaded.
[07:00:12][FileMgr] ERROR: Cannot find 'wificonfig.json' for reading. File does not exist.
[07:00:12][FileMgr] SD file: 'wificonfig.json' not found.
[07:00:12][FileMgr] Configuration File: '/admininfo.json' saved 168 bytes.
[07:00:12][FPP Remote] Start FPP Remote Task
[07:00:12][FileMgr] Configuration File: '/config.json' saved 525 bytes.
[07:00:13][WiFiDrv] WiFi Entering State: Connecting Using Config Credentials
[07:00:13][WiFiDrv] Using DHCP
[07:00:13][WiFiDrv] Connecting to 'xlights' as OUTSIDE
[07:00:14][WiFiDrv] WiFi Entering State: Connected To AP
[07:00:14][WiFiDrv] Connected with IP: 192.168.5.24
[07:00:14][   DDP] Listening on port 4048
[07:00:14][WebMgr] Web server listening on port 80
[07:00:14][FileMgr] Starting FTP server.
[07:00:14][  FPPD] FPPDiscovery subscribed to broadcast messages on port: 32320
[07:00:14][  FPPD] FPPDiscovery subscribed to multicast: 239.70.80.80:32320
[07:00:18][FileMgr] Upload File: 'donkey-xlight-2015.fseq' Started
[07:00:18]
[07:00:18]abort() was called at PC 0x4018969f on core 1
[07:00:18]
[07:00:18]
[07:00:18]Backtrace: 0x400845f9:0x3ffb4640 0x4008ebe5:0x3ffb4660 0x40094df5:0x3ffb4680 0x4018969f:0x3ffb4700 0x401896e6:0x3ffb4720 0x401894f3:0x3ffb4740 0x400e4d92:0x3ffb4760 0x400e5253:0x3ffb4780 0x400e52cf:0x3ffb47a0
[07:00:18]
[07:00:18]
[07:00:18]
[07:00:18]
[07:00:18]ELF file SHA256: 1f5aca334ef7a193
[07:00:18]
[07:00:18]E (9163) esp_core_dump_flash: Core dump flash config is corrupted! CRC=0x7bd5c66f instead of 0x0
[07:00:18]Rebooting...
[07:00:18]ets Jul 29 2019 12:21:46
[07:00:18]

**Comment by MartinMueller2003** [comment]
After a few days of debugging, I found the issue.
With FPP Remote enabled, I just finished a 22 minute FPP Connect session in which 12 files were uploaded without any issues.
Experimental build on the web flasher has been updated

**Comment by noman1228** [comment]
You are a God amongst men. Success when built or web flashed.
